---
Onnx_Status: true
Qat_Test: false
AISegment_352:
  datapath: /data_ssd
  ai85unetlarge:
    threshold: -5
    epoch: 15
CamVid_s352_c3:
  datapath: /data_ssd
  ai85unetlarge:
    threshold: -5
    epoch: 15
cats_vs_dogs:
  datapath: /data_ssd
  ai85cdnet:
    threshold: -5
    epoch: 15
CIFAR10:
  datapath: "/data_ssd"
  ai85nascifarnet:
    threshold: -5
    epoch: 15
  ai85net6:
    threshold: -5
    epoch: 15
  ai85squeezenet:
    threshold: -5
    epoch: 15
CIFAR100:
  datapath: "/data_ssd"
  ai85simplenet:
    threshold: -5
    epoch: 15
  ai85nascifarnet:
    threshold: -5
    epoch: 15
  ai87effnetv2:
    threshold: -5
    epoch: 15
  ai87netmobilenetv2cifar100_m0_5:
    threshold: -5
    epoch: 15
  ai87netmobilenetv2cifar100_m0_75:
    threshold: -5
    epoch: 15
  ai85ressimplenet:
    threshold: -5
    epoch: 15
  ai85simplenetwide2x:
    threshold: -5
    epoch: 15
ImageNet:
  datapath: "/data_ssd"
  ai87imageneteffnetv2:
    threshold: -5
    epoch: 15
ImageNet_Bayer:
  datapath: "/data_ssd"
  bayer2rgbnet:
    threshold: -5
    epoch: 15
KWS_20:
  datapath: "/data_ssd"
  ai85kws20net:
    threshold: -5
    epoch: 15
  ai85kws20netv2:
    threshold: -5
    epoch: 15
  ai85kws20netv3:
    threshold: -5
    epoch: 15
  ai87kws20netv3:
    threshold: -5
    epoch: 15
MNIST:
  datapath: "/data_ssd"
  ai85netextrasmall:
    threshold: -5
    epoch: 15
  ai85net5:
    threshold: -500
    epoch: 15
SVHN_74:
  datapath: "/data_ssd"
  ai85tinierssd:
    threshold: -500
    epoch: 15
PascalVOC_2007_2012_256_320_augmented:
  datapath: "/data_ssd"
  ai87fpndetector:
    threshold: -500
    epoch: 15
Kinetics400:
  datapath: "/data_ssd"
  ai85actiontcn:
    threshold: -500
    epoch: 15
