name: Trigger External Workflow

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the repository is a specific repository and branch
        run: |
          echo "IS_SPECIFIC_REPOSITORY=${{ github.repository == 'asyatrhl/ai8x-training' }}" >> $GITHUB_ENV
          echo "IS_DEVELOP_BRANCH=${{ github.ref == 'refs/heads/main_test_fork' }}" >> $GITHUB_ENV

      - name: Set up environment
        if: env.IS_SPECIFIC_REPOSITORY == 'true' && env.IS_DEVELOP_BRANCH == 'true'
        run: |
          PR_Branch=${{ github.event.pull_request.head.ref }}
          Repository=${{ github.repository }}
          PR_Number=${{ github.event.pull_request.number }}
          PR_Sha=${{ github.event.pull_request.head.sha }}
          echo "PR_Branch: $PR_Branch"
          echo "Repository: $Repository"
          echo "PR_Number: $PR_Number"
          echo "PR_Sha: $PR_Sha"

      - name: Dispatch event
        if: env.IS_SPECIFIC_REPOSITORY == 'true' && env.IS_DEVELOP_BRANCH == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.REGRESSION_TEST }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/asyatrhl/ai8x-regression/dispatches" \
            -d '{"event_type": "repo-pull-request", "client_payload": {"PR_Branch": "${{ github.event.pull_request.head.ref }}", "Repository": "${{ github.repository }}","PR_Number": "${{ github.event.pull_request.number }}","PR_Sha": "${{ github.event.pull_request.head.sha }}" }'
